In [1]:
import nltk
from nltk.stem.lancaster import LancasterStemmer
import numpy as np
# import tflearn
import tensorflow as tf
import json
import random
# import keras
import sklearn
print(tf.__version__)

2.0.0


In [2]:
stemmer = LancasterStemmer()

with open("intents.json") as file:
    data = json.load(file)

print(data["intents"])

[{'tag': 'greeting', 'patterns': ['Hi', 'How are you', 'Is anyone there?', 'Hello', 'Good day', 'Whats up'], 'responses': ['Hello!', 'Good to see you again!', 'Hi there, how can I help?'], 'context_set': ''}, {'tag': 'goodbye', 'patterns': ['cya', 'See you later', 'Goodbye', 'I am Leaving', 'Have a Good day'], 'responses': ['Sad to see you go :(', 'Talk to you later', 'Goodbye!'], 'context_set': ''}, {'tag': 'age', 'patterns': ['how old', 'how old is tim', 'what is your age', 'how old are you', 'age?'], 'responses': ['I am 18 years old!', '18 years young!'], 'context_set': ''}, {'tag': 'name', 'patterns': ['what is your name', 'what should I call you', 'whats your name?'], 'responses': ['You can call me Tim.', "I'm Tim!", "I'm Tim aka Tech With Tim."], 'context_set': ''}, {'tag': 'shop', 'patterns': ['Id like to buy something', 'whats on the menu', 'what do you reccommend?', 'could i get something to eat'], 'responses': ['We sell chocolate chip cookies for $2!', 'Cookies are on the men

In [3]:
words=[]
labels=[]
responses=[]
sentences=[]
sentence_labels=[]

In [4]:
print(data)

{'intents': [{'tag': 'greeting', 'patterns': ['Hi', 'How are you', 'Is anyone there?', 'Hello', 'Good day', 'Whats up'], 'responses': ['Hello!', 'Good to see you again!', 'Hi there, how can I help?'], 'context_set': ''}, {'tag': 'goodbye', 'patterns': ['cya', 'See you later', 'Goodbye', 'I am Leaving', 'Have a Good day'], 'responses': ['Sad to see you go :(', 'Talk to you later', 'Goodbye!'], 'context_set': ''}, {'tag': 'age', 'patterns': ['how old', 'how old is tim', 'what is your age', 'how old are you', 'age?'], 'responses': ['I am 18 years old!', '18 years young!'], 'context_set': ''}, {'tag': 'name', 'patterns': ['what is your name', 'what should I call you', 'whats your name?'], 'responses': ['You can call me Tim.', "I'm Tim!", "I'm Tim aka Tech With Tim."], 'context_set': ''}, {'tag': 'shop', 'patterns': ['Id like to buy something', 'whats on the menu', 'what do you reccommend?', 'could i get something to eat'], 'responses': ['We sell chocolate chip cookies for $2!', 'Cookies ar

In [5]:
from nltk.tokenize import word_tokenize

for intent_dict in data["intents"]:
    temp=[]
    for sentence in intent_dict["patterns"]:
        print(sentence)
        w = word_tokenize(sentence)
        temp+=w
        sentences+=[sentence]
        sentence_labels+=[intent_dict["tag"]]
    words+=[temp]
    if intent_dict["tag"] not in labels:
        labels+=[intent_dict["tag"]]
    responses+=[intent_dict["responses"]]

Hi
How are you
Is anyone there?
Hello
Good day
Whats up
cya
See you later
Goodbye
I am Leaving
Have a Good day
how old
how old is tim
what is your age
how old are you
age?
what is your name
what should I call you
whats your name?
Id like to buy something
whats on the menu
what do you reccommend?
could i get something to eat
when are you guys open
what are your hours
hours of operation


In [6]:
print(words)

[['Hi', 'How', 'are', 'you', 'Is', 'anyone', 'there', '?', 'Hello', 'Good', 'day', 'Whats', 'up'], ['cya', 'See', 'you', 'later', 'Goodbye', 'I', 'am', 'Leaving', 'Have', 'a', 'Good', 'day'], ['how', 'old', 'how', 'old', 'is', 'tim', 'what', 'is', 'your', 'age', 'how', 'old', 'are', 'you', 'age', '?'], ['what', 'is', 'your', 'name', 'what', 'should', 'I', 'call', 'you', 'whats', 'your', 'name', '?'], ['Id', 'like', 'to', 'buy', 'something', 'whats', 'on', 'the', 'menu', 'what', 'do', 'you', 'reccommend', '?', 'could', 'i', 'get', 'something', 'to', 'eat'], ['when', 'are', 'you', 'guys', 'open', 'what', 'are', 'your', 'hours', 'hours', 'of', 'operation']]


In [7]:
words_flatten=[w for sub_list in words for w in sub_list]

In [8]:
print(words_flatten)

['Hi', 'How', 'are', 'you', 'Is', 'anyone', 'there', '?', 'Hello', 'Good', 'day', 'Whats', 'up', 'cya', 'See', 'you', 'later', 'Goodbye', 'I', 'am', 'Leaving', 'Have', 'a', 'Good', 'day', 'how', 'old', 'how', 'old', 'is', 'tim', 'what', 'is', 'your', 'age', 'how', 'old', 'are', 'you', 'age', '?', 'what', 'is', 'your', 'name', 'what', 'should', 'I', 'call', 'you', 'whats', 'your', 'name', '?', 'Id', 'like', 'to', 'buy', 'something', 'whats', 'on', 'the', 'menu', 'what', 'do', 'you', 'reccommend', '?', 'could', 'i', 'get', 'something', 'to', 'eat', 'when', 'are', 'you', 'guys', 'open', 'what', 'are', 'your', 'hours', 'hours', 'of', 'operation']


In [9]:
print(labels)

['greeting', 'goodbye', 'age', 'name', 'shop', 'hours']


In [10]:
print(f"{labels[0]}\n\n{words[0]}\n\n{responses[0]}")

greeting

['Hi', 'How', 'are', 'you', 'Is', 'anyone', 'there', '?', 'Hello', 'Good', 'day', 'Whats', 'up']

['Hello!', 'Good to see you again!', 'Hi there, how can I help?']


In [11]:
words_flatten=sorted(list(set([stemmer.stem(w.lower()) for w in words_flatten])))

In [12]:
print(words_flatten)

['?', 'a', 'ag', 'am', 'anyon', 'ar', 'buy', 'cal', 'could', 'cya', 'day', 'do', 'eat', 'get', 'good', 'goodby', 'guy', 'hav', 'hello', 'hi', 'hour', 'how', 'i', 'id', 'is', 'lat', 'leav', 'lik', 'menu', 'nam', 'of', 'old', 'on', 'op', 'reccommend', 'see', 'should', 'someth', 'the', 'ther', 'tim', 'to', 'up', 'what', 'when', 'yo', 'you']


In [13]:
print(len(words_flatten))

47


In [14]:
 print(sentences)

['Hi', 'How are you', 'Is anyone there?', 'Hello', 'Good day', 'Whats up', 'cya', 'See you later', 'Goodbye', 'I am Leaving', 'Have a Good day', 'how old', 'how old is tim', 'what is your age', 'how old are you', 'age?', 'what is your name', 'what should I call you', 'whats your name?', 'Id like to buy something', 'whats on the menu', 'what do you reccommend?', 'could i get something to eat', 'when are you guys open', 'what are your hours', 'hours of operation']


In [15]:
print(sentence_labels)

['greeting', 'greeting', 'greeting', 'greeting', 'greeting', 'greeting', 'goodbye', 'goodbye', 'goodbye', 'goodbye', 'goodbye', 'age', 'age', 'age', 'age', 'age', 'name', 'name', 'name', 'shop', 'shop', 'shop', 'shop', 'hours', 'hours', 'hours']


In [16]:
labels.sort()
labels

['age', 'goodbye', 'greeting', 'hours', 'name', 'shop']

In [17]:
print(len(sentences), len(sentence_labels))

26 26


In [18]:
from sklearn.preprocessing import LabelBinarizer
enc = LabelBinarizer()
sentence_labels_oh = enc.fit_transform(np.array(sentence_labels))

In [19]:
print(sentence_labels_oh)

[[0 0 1 0 0 0]
 [0 0 1 0 0 0]
 [0 0 1 0 0 0]
 [0 0 1 0 0 0]
 [0 0 1 0 0 0]
 [0 0 1 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 1 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]
 [0 0 0 1 0 0]
 [0 0 0 1 0 0]
 [0 0 0 1 0 0]]


In [20]:
for i in range(26):
    print(f"{sentence_labels[i]}\t{sentence_labels_oh[i]}")

greeting	[0 0 1 0 0 0]
greeting	[0 0 1 0 0 0]
greeting	[0 0 1 0 0 0]
greeting	[0 0 1 0 0 0]
greeting	[0 0 1 0 0 0]
greeting	[0 0 1 0 0 0]
goodbye	[0 1 0 0 0 0]
goodbye	[0 1 0 0 0 0]
goodbye	[0 1 0 0 0 0]
goodbye	[0 1 0 0 0 0]
goodbye	[0 1 0 0 0 0]
age	[1 0 0 0 0 0]
age	[1 0 0 0 0 0]
age	[1 0 0 0 0 0]
age	[1 0 0 0 0 0]
age	[1 0 0 0 0 0]
name	[0 0 0 0 1 0]
name	[0 0 0 0 1 0]
name	[0 0 0 0 1 0]
shop	[0 0 0 0 0 1]
shop	[0 0 0 0 0 1]
shop	[0 0 0 0 0 1]
shop	[0 0 0 0 0 1]
hours	[0 0 0 1 0 0]
hours	[0 0 0 1 0 0]
hours	[0 0 0 1 0 0]


In [1]:
# count vectorizer is used to make BoW ( Bag of Words)

In [21]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(stop_words='english')
vectorizer.fit(words_flatten)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words='english',
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [22]:
vectorizer.vocabulary_

{'ag': 0,
 'anyon': 1,
 'ar': 2,
 'buy': 3,
 'cal': 4,
 'cya': 5,
 'day': 6,
 'eat': 7,
 'good': 8,
 'goodby': 9,
 'guy': 10,
 'hav': 11,
 'hello': 12,
 'hi': 13,
 'hour': 14,
 'id': 15,
 'lat': 16,
 'leav': 17,
 'lik': 18,
 'menu': 19,
 'nam': 20,
 'old': 21,
 'op': 22,
 'reccommend': 23,
 'someth': 24,
 'ther': 25,
 'tim': 26,
 'yo': 27}

In [23]:
sentences_stemmed=[]
for s in sentences:
    w = word_tokenize(s)
#     print(w)
    temp= ""
    for j in w:
#         print(f" j ={j}")
        temp+=stemmer.stem(j.lower())+" "
#         print(temp)
    sentences_stemmed+=[temp]
#     print(f"sentences_stemmed = {sentences_stemmed}")

In [24]:
print(sentences_stemmed)

['hi ', 'how ar you ', 'is anyon ther ? ', 'hello ', 'good day ', 'what up ', 'cya ', 'see you lat ', 'goodby ', 'i am leav ', 'hav a good day ', 'how old ', 'how old is tim ', 'what is yo ag ', 'how old ar you ', 'ag ? ', 'what is yo nam ', 'what should i cal you ', 'what yo nam ? ', 'id lik to buy someth ', 'what on the menu ', 'what do you reccommend ? ', 'could i get someth to eat ', 'when ar you guy op ', 'what ar yo hour ', 'hour of op ']


In [25]:
sentence_vectors = vectorizer.fit_transform(sentences_stemmed)

In [26]:
print(sentence_vectors)

  (0, 13)	1
  (1, 2)	1
  (2, 1)	1
  (2, 25)	1
  (3, 12)	1
  (4, 8)	1
  (4, 6)	1
  (6, 5)	1
  (7, 16)	1
  (8, 9)	1
  (9, 17)	1
  (10, 8)	1
  (10, 6)	1
  (10, 11)	1
  (11, 21)	1
  (12, 21)	1
  (12, 26)	1
  (13, 27)	1
  (13, 0)	1
  (14, 2)	1
  (14, 21)	1
  (15, 0)	1
  (16, 27)	1
  (16, 20)	1
  (17, 4)	1
  (18, 27)	1
  (18, 20)	1
  (19, 15)	1
  (19, 18)	1
  (19, 3)	1
  (19, 24)	1
  (20, 19)	1
  (21, 23)	1
  (22, 24)	1
  (22, 7)	1
  (23, 2)	1
  (23, 10)	1
  (23, 22)	1
  (24, 2)	1
  (24, 27)	1
  (24, 14)	1
  (25, 22)	1
  (25, 14)	1


In [27]:
sentence_vectors=sentence_vectors.toarray()

In [28]:
print(sentence_vectors)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 

In [29]:
X_train = sentence_vectors.copy()
Y_train = sentence_labels_oh.copy()

In [30]:
print(type(sentence_labels_oh))

<class 'numpy.ndarray'>


In [31]:
# from sklearn.model_selection import train_test_split
# X_train ,X_test, Y_train, Y_test=train_test_split(X,Y, test_size=0.1)

In [32]:
print(X_train.shape, Y_train.shape)

(26, 28) (26, 6)


In [33]:
# print(X_test.shape, Y_test.shape)

In [34]:
vectorizer.vocabulary_

{'hi': 13,
 'ar': 2,
 'anyon': 1,
 'ther': 25,
 'hello': 12,
 'good': 8,
 'day': 6,
 'cya': 5,
 'lat': 16,
 'goodby': 9,
 'leav': 17,
 'hav': 11,
 'old': 21,
 'tim': 26,
 'yo': 27,
 'ag': 0,
 'nam': 20,
 'cal': 4,
 'id': 15,
 'lik': 18,
 'buy': 3,
 'someth': 24,
 'menu': 19,
 'reccommend': 23,
 'eat': 7,
 'guy': 10,
 'op': 22,
 'hour': 14}

In [35]:
model = tf.keras.models.Sequential([
    tf.keras.Input(shape=X_train.shape[1]),
    tf.keras.layers.Dense(8 , activation='relu', kernel_regularizer=tf.keras.regularizers.l2(0.01)),
    tf.keras.layers.Dense(8 , activation='relu',kernel_regularizer=tf.keras.regularizers.l2(0.01)),
    tf.keras.layers.Dense(Y_train.shape[1], activation='softmax')
  ])

In [36]:
# help(tf.keras.Input)

In [37]:
model.compile(optimizer='adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 8)                 232       
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_2 (Dense)              (None, 6)                 54        
Total params: 358
Trainable params: 358
Non-trainable params: 0
_________________________________________________________________


In [38]:
history = model.fit(x=X_train, y = Y_train, epochs=200,batch_size=8)

Train on 26 samples
Epoch 1/200
26/26 [==============================] - 1s 22ms/sample - loss: 1.9767 - accuracy: 0.2308
Epoch 2/200
26/26 [==============================] - 0s 285us/sample - loss: 1.9677 - accuracy: 0.1923
Epoch 3/200
26/26 [==============================] - 0s 265us/sample - loss: 1.9600 - accuracy: 0.1923
Epoch 4/200
26/26 [==============================] - 0s 317us/sample - loss: 1.9523 - accuracy: 0.1923
Epoch 5/200
26/26 [==============================] - 0s 357us/sample - loss: 1.9456 - accuracy: 0.2692
Epoch 6/200
26/26 [==============================] - 0s 342us/sample - loss: 1.9389 - accuracy: 0.2692
Epoch 7/200
26/26 [==============================] - 0s 433us/sample - loss: 1.9323 - accuracy: 0.3077
Epoch 8/200
26/26 [==============================] - 0s 314us/sample - loss: 1.9257 - accuracy: 0.3462
Epoch 9/200
26/26 [==============================] - 0s 345us/sample - loss: 1.9196 - accuracy: 0.3462
Epoch 10/200
26/26 [==============================] - 

26/26 [==============================] - 0s 333us/sample - loss: 0.9146 - accuracy: 0.7308
Epoch 157/200
26/26 [==============================] - 0s 332us/sample - loss: 0.9084 - accuracy: 0.7308
Epoch 158/200
26/26 [==============================] - 0s 287us/sample - loss: 0.9021 - accuracy: 0.7308
Epoch 159/200
26/26 [==============================] - 0s 316us/sample - loss: 0.8955 - accuracy: 0.7308
Epoch 160/200
26/26 [==============================] - 0s 319us/sample - loss: 0.8901 - accuracy: 0.7308
Epoch 161/200
26/26 [==============================] - 0s 352us/sample - loss: 0.8831 - accuracy: 0.7308
Epoch 162/200
26/26 [==============================] - 0s 324us/sample - loss: 0.8776 - accuracy: 0.7308
Epoch 163/200
26/26 [==============================] - 0s 321us/sample - loss: 0.8709 - accuracy: 0.7308
Epoch 164/200
26/26 [==============================] - 0s 320us/sample - loss: 0.8651 - accuracy: 0.7308
Epoch 165/200
26/26 [==============================] - 0s 322us/sampl

In [39]:
print(history.history)

{'loss': [1.976697481595553, 1.9676528710585375, 1.9600413670906653, 1.9523000166966364, 1.9456395552708552, 1.9388873393719013, 1.9323147443624644, 1.9256793168874888, 1.919626997067378, 1.913562114422138, 1.9082141656142015, 1.9021167296629686, 1.8969718859745905, 1.891498400614812, 1.885767441529494, 1.8806917667388916, 1.8742184547277598, 1.868685089624845, 1.8632248823459332, 1.857896557221046, 1.852406538449801, 1.847080716719994, 1.8421980234292836, 1.8361180195441613, 1.8311848732141347, 1.8252295072262104, 1.8197740224691539, 1.8145106480671809, 1.8093336270405695, 1.8041676741379957, 1.7990943835331843, 1.7931827490146344, 1.787970937215365, 1.7816606943423932, 1.7763689756393433, 1.7704485654830933, 1.7655618282464833, 1.7597366204628577, 1.7541107214414156, 1.7484883345090425, 1.7423878908157349, 1.7370889645356398, 1.731196614412161, 1.7248651156058679, 1.7193129062652588, 1.7138005678470318, 1.7081919358326838, 1.7026165081904485, 1.6966311106315026, 1.6914721085475042, 1

In [40]:
# model.evaluate(X_test,Y_test)

In [42]:
from time import time, ctime
# ctime(time())
model.save("model "+ctime(time()))

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
INFO:tensorflow:Assets written to: model Sat Dec 28 11:20:09 2019/assets


In [78]:
print(vectorizer.vocabulary_)

{'hi': 13, 'ar': 2, 'anyon': 1, 'ther': 25, 'hello': 12, 'good': 8, 'day': 6, 'cya': 5, 'lat': 16, 'goodby': 9, 'leav': 17, 'hav': 11, 'old': 21, 'tim': 26, 'yo': 27, 'ag': 0, 'nam': 20, 'cal': 4, 'id': 15, 'lik': 18, 'buy': 3, 'someth': 24, 'menu': 19, 'reccommend': 23, 'eat': 7, 'guy': 10, 'op': 22, 'hour': 14}


In [77]:
print(sorted(list(vectorizer.vocabulary_.keys())))

['ag', 'anyon', 'ar', 'buy', 'cal', 'cya', 'day', 'eat', 'good', 'goodby', 'guy', 'hav', 'hello', 'hi', 'hour', 'id', 'lat', 'leav', 'lik', 'menu', 'nam', 'old', 'op', 'reccommend', 'someth', 'ther', 'tim', 'yo']


In [91]:
def bag_of_words(s, dict_word):
    bag = [0 for _ in range(len(dict_word))]

    s_words = nltk.word_tokenize(s)
    s_words = [stemmer.stem(word.lower()) for word in s_words]
#     print(s_words)
    for se in s_words:
        if se in dict_word.keys():
            bag[dict_word[se]]=1
            
    return np.array(bag)


def chat(word_dict):
    print("Start talking with the bot (type quit to stop)!")
    while True:
        inp = input("You: ")
        if "quit" in inp.lower():
            break
#         print(bag_of_words(inp, word_dict).shape, bag_of_words(inp, word_dict))
        results = model.predict(bag_of_words(inp, word_dict).reshape(1,-1))
        results_index = np.argmax(results)
        tag = labels[results_index]

        for tg in data["intents"]:
            if tg['tag'] == tag:
                responses = tg['responses']

        print(np.random.choice(responses))

chat(vectorizer.vocabulary_)

Start talking with the bot (type quit to stop)!
You: quit()
